apiVersion: v1
kind: Service
metadata:
  labels:
    app: modeldb
  name: modeldb-backend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8085
  selector:
    app: modeldb
    tier: backend
  type: {{ .Values.service.modeldbBackendService }}