apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: modeldb
  name: modeldb-webapp
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: modeldb
    tier: webapp
  type: LoadBalancer