apiVersion: v1
kind: Service
metadata:
  annotations:
  name: modeldb-mysql-backend
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: modeldb
    tier: mysql
  type: ClusterIP