apiVersion: v1
kind: Service
metadata:
  labels:
    app: modeldb
  name: modeldb-artifact-store
  namespace: default
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: modeldb
    tier: artifact-store
  type: ClusterIP