apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: modeldb
  name: modeldb-mysql-pv-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi