apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modeldb
  name: modeldb-backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: modeldb
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeldb
        tier: backend
    spec:
      containers:
      - env:
        - name: VERTA_MODELDB_CONFIG
          value: /config-backend/config.yaml
        image: acshanth/modeldb-backend:v3
        imagePullPolicy: Always
        name: modeldb-backend
        ports:
        - containerPort: 8085
        volumeMounts:
        - mountPath: /config-backend
          name: modeldb-backend-secret-volume
          readOnly: true
      volumes:
      - name: modeldb-backend-secret-volume
        secret:
          secretName: modeldb-backend-config-secret

