apiVersion: v1
kind: Service
metadata:
  labels:
    app: modeldb
  name: modeldb-backend
  namespace: default
spec:
  ports:
  - port: 8085
  selector:
    app: modeldb
    tier: backend
  type: LoadBalancer